pipeline {
    agent any

    stages {

        stage('Build Backend') {
            steps {
                sh '''
                cd emp_mng
                docker build -t emp-backend ./backend
                '''
            }
        }

        stage('Build Frontend') {
    steps {
        sh '''
        cd emp_mng
        docker build -t emp-frontend ./frontend
        '''
    }
}

stage('List Images') {
    steps {
        sh 'docker images'
    }
}

stage('Docker Login') {
    steps {
        withCredentials([
            usernamePassword(
                credentialsId: 'docker_cred',
                usernameVariable: 'DOCKER_USER',
                passwordVariable: 'DOCKER_PASS'
            )
        ]) {
            sh '''
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            '''
        }
    }
}

stage('Tag Images') {
    steps {
        sh '''
        docker tag emp-backend pratik4106/emp_mng-backend:${BUILD_NUMBER}
        docker tag emp-frontend pratik4106/emp_mng-frontend:${BUILD_NUMBER}
        '''
    }
}

stage('Push Images') {
    steps {
        sh '''
        docker push pratik4106/emp_mng-backend:${BUILD_NUMBER}
        docker push pratik4106/emp_mng-frontend:${BUILD_NUMBER}
        '''
    }
}

stage('Build Info') {
    steps {
        echo "Build Number: ${BUILD_NUMBER}"
    }
}

stage('Deploy') {
    steps {
        sh '''
        kubectl set image deployment/backend \
        backend=pratik4106/emp_mng-backend:${BUILD_NUMBER}

        kubectl set image deployment/frontend \
        frontend=pratik4106/emp_mng-frontend:${BUILD_NUMBER}

        kubectl rollout status deployment/backend
        kubectl rollout status deployment/frontend
        '''
    }
}
    }
}