pipeline {
    agent any

    stages {

        stage('Build Backend') {
            steps {
                sh '''
                cd emp_mng
                docker build -t emp-backend ./backend
                '''
            }
        }

        stage('Build Frontend') {
    steps {
        sh '''
        cd emp_mng
        docker build -t emp-frontend ./frontend
        '''
    }
}

stage('List Images') {
    steps {
        sh 'docker images'
    }
}

stage('Docker Login') {
    steps {
        withCredentials([
            usernamePassword(
                credentialsId: 'dockerhub-creds',
                usernameVariable: 'DOCKER_USER',
                passwordVariable: 'DOCKER_PASS'
            )
        ]) {
            sh '''
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            '''
        }
    }
}

stage('Tag Images') {
    steps {
        sh '''
        docker tag emp-backend pratik4106/emp_mng-backend:v2
        docker tag emp-frontend pratik4106/emp_mng-frontend:v2
        '''
    }
}

stage('Push Images') {
    steps {
        sh '''
        docker push pratik4106/emp_mng-backend:v2
        docker push pratik4106/emp_mng-frontend:v2
        '''
    }
}
    }
}